discord:
  - id: "newsubs"
    discord_channel: "newsubs"
    discord_username: "zereef_sec"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/1158350505655930922/TqshLls7thir3FxpOt-GB20m9agtR_JlHGaqiYvz04lRwfUJMatHGeuHvUS0hqgmiezl"

  - id: "subtkovr"
    discord_channel: "subdomain-takeover"
    discord_username: "zereef_sec"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/1158619594920038481/FYuE11OD6jIqbqntNQUBn_y2dhillvuzc4-jE3zet0XEpQGS9VWiguqTisAwP06iUaKe"
